In [ ]:
#question 1

A Python library is a collection of pre-written code, functions, classes, and modules that you can use to perform specific tasks without having to write the code from scratch. These libraries are bundled into a single package, making it easier for developers to implement complex functionalities efficiently.

Why do we use Python Library

1. Code Reusability
2. Faster development
3. Community support
4. Specialized Functionality
5. Optimization
6. Better Organization

In [ ]:
#question 2

A NumPy Array and a Python List differ significantly in terms of data handling, performance, and functionality. While a Python list can store elements of different data types, a NumPy array requires all elements to be of the same type, which allows for more efficient memory usage and faster operations. NumPy arrays are optimized for numerical computations, supporting vectorized operations that perform calculations on entire arrays at once, making them much faster for large-scale data processing compared to Python lists, which require loops for element-wise operations. Additionally, NumPy arrays support multi-dimensional data structures, such as matrices or higher-dimensional arrays, and come with a wide range of mathematical functions, which Python lists lack. Lists in Python, on the other hand, are more flexible, allowing dynamic resizing and holding mixed types, but they are less memory-efficient and slower when handling numerical tasks. In terms of scientific computing, NumPy excels with specialized features for linear algebra, random number generation, and more, while Python lists remain general-purpose containers, suitable for a wide variety of tasks but not designed for complex numerical operations. Overall, while Python lists are versatile and suitable for basic data storage, NumPy arrays are the preferred choice for performance-intensive operations and scientific computing.

In [ ]:
#question 3

In [1]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Finding shape, size, and dimension
shape = array.shape  # Shape of the array
size = array.size    # Total number of elements
dim = array.ndim     # Number of dimensions

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dim)


Shape: (3, 4)
Size: 12
Dimension: 2


In [ ]:
#question 4

In [2]:
# Accessing the first row
first_row = array[0] 
print("First Row:", first_row)


First Row: [1 2 3 4]


In [ ]:
#question 5

In [3]:
# Accessing the element at the 3rd row and 4th column
element = array[2, 3]  # Indexing starts from 0, so [2, 3] refers to the 3rd row, 4th column
print("Element at third row and fourth column:", element)

Element at third row and fourth column: 12


In [ ]:
#question 6

In [4]:
# Extracting all odd-indexed elements
odd_elements = array[1::2, 1::2]  # Slicing rows and columns starting from index 1 with a step of 2
print("Odd-indexed elements:\n", odd_elements)


Odd-indexed elements:
 [[6 8]]


In [ ]:
#question 7

In [5]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)
print("Random 3x3 Matrix:\n", random_matrix)

Random 3x3 Matrix:
 [[0.6951791  0.27354945 0.72454336]
 [0.69197996 0.89734105 0.98552611]
 [0.12324192 0.63169528 0.28754974]]


In [ ]:
#question 8

The main difference between np.random.rand and np.random.randn lies in the distribution of the generated values. The function np.random.rand generates random values that are uniformly distributed between 0 and 1, meaning all values within this range are equally likely to occur. On the other hand, np.random.randn generates random values from a standard normal distribution, also known as a Gaussian distribution, where the mean is 0 and the standard deviation is 1. In this case, the values are more likely to cluster around 0, with fewer values occurring as they deviate further from the mean. Both functions take the dimensions of the desired array as arguments, but they are used for different purposes: np.random.rand is ideal for generating random values in a fixed range (e.g., probabilities or weights), while np.random.randn is used for applications requiring normally distributed data, such as statistical modeling or machine learning initialization.

In [ ]:
#question 9

In [6]:
import numpy as np

# Original array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Increase dimension using np.expand_dims
increased_dim_1 = np.expand_dims(array, axis=0)  # Add a new axis at the front
print("Increased Dimension (axis=0):\n", increased_dim_1)

Increased Dimension (axis=0):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
#question 10

In [7]:
# Transpose the array
transposed_array = array.T 
print("Transposed Array:\n", transposed_array)


Transposed Array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
#question 11

In [8]:
import numpy as np

# Define matrices
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 1. Index-wise Multiplication
index_wise_multiplication = A * B
print("Index-wise Multiplication:\n", index_wise_multiplication)

# 2. Matrix Multiplication
matrix_multiplication = np.dot(A, B.T)  # Transpose B for matrix multiplication
print("Matrix Multiplication:\n", matrix_multiplication)

# 3. Add Both Matrices
matrix_addition = A + B
print("Addition of Matrices:\n", matrix_addition)

# 4. Subtract Matrix B from Matrix A
matrix_subtraction = A - B
print("Subtraction (A - B):\n", matrix_subtraction)

# 5. Divide Matrix B by Matrix A
matrix_division = B / A
print("Division of Matrices (B / A):\n", matrix_division)

Index-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition of Matrices:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction (A - B):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of Matrices (B / A):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#question 12

The np.ndarray.byteswap() function is used to swap the byte order of an array. This is particularly useful when working with data stored in a format with a different endianness than the current system.

In [ ]:
#question 13

 This function is widely used in linear algebra and applications like solving systems of linear equations.

1. It allows for solving matrix equations of the form AX = B by computing X = A^-1 B
2. It is essential for various numerical and computational algorithms in data science, machine learning, and engineering.

In [ ]:
#question 14

The np.reshape function changes the shape of an existing NumPy array without modifying its data. It allows you to rearrange the elements of an array into a new shape, provided the total number of elements remains the same.

Usage:
1. Rearrange a flat array into a multi-dimensional array or vice versa.
2. Change the dimensions of an array to fit specific requirements (e.g., reshaping for machine learning models).

In [ ]:
#question 15

Broadcasting is a powerful feature in NumPy that allows operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger array. This eliminates the need for manual replication of data and makes operations more efficient.